name: Xcode Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build Project
        run: |
          xcodebuild clean build \
            -project "CashAppSpoof.xcodeproj" \
            -scheme "CashAppSpoof" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
